import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import './globals.css'
import Providers from './providers'
import Navigator from '@/components/Navigator'
import { TwMerge } from '@/lib/tailwind'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({
  children,
}: {
  children: React.ReactNode
}) => {
  return (
    <html lang="es">
      <body className={TwMerge(inter.className, 'bg-gray-100 dark:bg-gray-900')}>
        <Providers>
          <Navigator />
          {children}
        </Providers>
      </body>
    </html>
  )
}

export default RootLayout
